version: '3.8'

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: redis_server
    ports:
      - "6379:6379"
